import { chromium } from "@playwright/test";
const URL = "https://aurelius-production-3c6e.up.railway.app";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto(`${URL}/register`);
const email = `probe-${Date.now()}@aurelius.local`;
await page.getByLabel("Display name").fill("Probe");
await page.getByLabel("Email").fill(email);
await page.getByLabel("Password").fill("ProbeTest123");
await page.getByRole("button", { name: "Create Account" }).click();
await page.waitForURL("**/account**");
await page.goto(`${URL}/watches`);
await page.locator("article a").first().click();
await page.waitForURL("**/watches/**");
await page.waitForTimeout(1200);
await page.getByRole("button", { name: /Buy now/i }).first().click();
await page.waitForURL("**/checkout/**");
await page.getByLabel("Full name").fill("Probe");
await page.getByLabel("Address line 1").fill("1 Street");
await page.getByLabel("City").fill("London");
await page.getByLabel("Postal code").fill("W1 1AA");
await page.getByLabel("Country").fill("UK");
await page.getByLabel("Card number").fill("4242 4242 4242 4242");
await page.getByLabel("Cardholder name").fill("Probe");
await page.getByLabel("Expiry").fill("12/29");
await page.getByLabel("CVC").fill("123");
await page.getByRole("button", { name: /Pay .* & Place Order/i }).click();
await page.waitForTimeout(8000);
console.log("URL after pay:", page.url());
const main = await page.locator("main").innerText();
console.log("--- order page text (first 500):");
console.log(main.slice(0, 500));
await page.screenshot({ path: "test-results/probe-order.png", fullPage: true });
await browser.close();
